### ISSUE TITLE
SGDClassifier gets eta < 0 bug at tune

### ISSUE THREAD

**Issue by mikeDTI** [GenoML/genoml2#14]
<em>Please make sure that this is a bug.</em>

**System information:**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- GenoML Installed from (source or binary): PIP'd ;-)
- GenoML Version: 1.5
- Python Version: 3.7

**Describe the current behavior:**
SGDClassifier gets eta < 0 bug at tune
`ValueError: eta0 must be > 0`

**Describe the expected behavior:**
eta0 must be > 0

**Code to reproduce the issue:**
See DementiaSeqML.

**Other Information / Logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[Archive.zip](https://github.com/GenoML/genoml2/files/5188755/Archive.zip)

To fix this, just need to make eta0 limits at tune if SGDC is the winning algorithm. 

Might be safe to change ...
`            elif  best_algo == 'SGDClassifier':
                hyperparameters = {'alpha': [1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1, 1e2, 1e3], "learning_rate": ["constant", "optimal", "invscaling", "adaptive"]}
                scoring_metric = metrics.make_scorer(metrics.balanced_accuracy_score, needs_proba=False)
`
To ...
`            elif  best_algo == 'SGDClassifier':
                hyperparameters = {
    'alpha': [1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1, 1e2, 1e3], # learning rate
    'n_iter': [1000], # number of epochs
    'loss': ['log'], # logistic regression,
    'penalty': ['l2'],
    'n_jobs': [-1]
}
                scoring_metric = metrics.make_scorer(metrics.balanced_accuracy_score, needs_proba=False)
`

**Comment by mikeDTI** [comment]
Then just re-edit for the AUC tuning option as well.

**Comment by m-makarious** [comment]
Managed to replicate this issue also on the test data available in `examples/` by commenting out the rest of the algorithms to compete against in training before I tried running the tuning script. 

Thanks to Mike's suggestion (with some minor tweaks) this issue has been resolved in the `discrete/supervised/tuning.py `script by modifying the lines in the tuning script so that the eta0 error doesn't pop up - both maximizing on AUC and balance accuracy have been tested. The most recent push reflects these changes.

---
### Screenshots of changes

**_Tuning on AUC:_** 
![image](https://user-images.githubusercontent.com/17086628/92526999-59da1480-f1f4-11ea-813d-cfadb7ef5b19.png)


**_Tuning on balanced accuracy:_**
![image](https://user-images.githubusercontent.com/17086628/92527065-6c544e00-f1f4-11ea-88f1-5dedd8b18bf6.png)

**Comment by mikeDTI** [comment]
You are a certified bug killer @Makarious, Mary (NIH/NINDS) [F]
<mary.makarious@nih.gov> !

*Mike A. Nalls, PhD*

*Data Tecnica International <http://www.datatecnica.com/>*
Note: I check emails only in bursts ... for immediate project specific
issues please use the relevant BaseCamp.
